# +++ TRAVIS-FILE for https://github.com/h-da/geli +++

# required for chrome to install
dist: trusty
# required for e2e tests to complete succesfully (page crash???)
sudo: required
language: node_js
node_js:
  - "7.9.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      # manually update dependencies for chrome
      - libfontconfig1
      - libstdc++6
      - lsb-base
      # used for frontend e2e tests
      - google-chrome-stable

services:
  - mongodb
  - docker

branches:
  only:
    - develop
    # Only for development purposes
    # - feature/14-travis-new

cache:
  directories:
    - api/node_modules
    - app/webFrontend/node_modules

before_script:
  # required for chrome to start properly
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # required for MongoDB to have time to start up
  - sleep 15

install:
  # install api and return back to root for following steps
  - cd api
  - npm install
  - npm prune          # remove not (anymore) in package.json required packages (to keep the cache clean)
  - cd ..
  # install frontend and return back to root for following steps
  - cd app/webFrontend
  - npm install
  - npm prune          # remove not (anymore) in package.json required packages (to keep the cache clean)
  - cd ../..

script:
  # run backend-tests and return back to root for following steps
  - cd api
  # - npm run tslint      # run linter | included in command test
  - npm run test        # run backend test
  - cd ..
  # run frontend-tests and return back to root for following steps
  # npm scripts won't work here (dunno why...)
  - cd app/webFrontend
  - npm run lint        # run linter
  # - npm run test        # run test - does not work properly
  - npm run e2e         # run end-to-end-tests
  - cd ../..
  - docker build -t hdafbi/geli_api -f .docker/api .
  - docker build -t hdafbi/geli_webserver -f .docker/webserver .

after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push hdafbi/geli_api;
  - docker push hdafbi/geli_webserver;
#    fi

notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOK_NOTIFY
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: always   # options: [always|never|change] default: always
    on_error: always    # options: [always|never|chnage] default: always
