# +++ TRAVIS-FILE for https://github.com/h-da/geli +++

# required for chrome to install
dist: trusty
# required for e2e tests to complete succesfully (page crash???)
sudo: required
language: node_js
node_js:
  - "7.9.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      # manually update dependencies for chrome
      - libfontconfig1
      - libstdc++6
      - lsb-base
      # used for frontend e2e tests
      - google-chrome-stable

services:
  - mongodb
  - docker

branches:
  only:
    - develop
    # Only for development purposes
    # - feature/14-travis-new

cache:
  directories:
    - api/node_modules
    - app/webFrontend/node_modules
    - .travis/node_modules

before_script:
  # required for chrome to start properly
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # required for MongoDB to have time to start up
  - sleep 15

install:
  # install api and return back to root for following steps
  - cd api
  - npm install
  - npm prune          # remove not (anymore) in package.json required packages (to keep the cache clean)
  - cd ..
  # install frontend and return back to root for following steps
  - cd app/webFrontend
  - npm install
  - npm prune          # remove not (anymore) in package.json required packages (to keep the cache clean)
  - cd ../..
  # install travis dependencies
  - cd .travis
  - npm install
  - npm prune
  - cd ..

script:
  # run backend-tests and return back to root for following steps
  - cd api
  - npm run test        # run backend test
  - cd ..
  # run frontend-tests and return back to root for following steps
  - cd app/webFrontend
  - npm run lint        # run linter
  # - npm run test        # run test - does not work properly
  - npm run e2e         # run end-to-end-tests
  - npm run build       # build in prod mode
  - cd ../..
  - docker build -t hdafbi/geli-api:latest -f .docker/api/Dockerfile .
  - docker tag hdafbi/geli-api hdafbi/geli-api:$TRAVIS_BRANCH
  - docker build -t hdafbi/geli-web-frontend:latest -f .docker/web-frontend/Dockerfile .
  - docker tag hdafbi/geli-web-frontend hdafbi/geli-web-frontend:$TRAVIS_BRANCH

after_success:
  - .travis/docker.sh

after_script:
  # add coveralls calls here
  # - coveralls stuff
  # run license checker (nlf) on branch develop
  # TODO: we should check if the build was triggered after accepting a PR to dev and only then run
  - test $TRAVIS_BRANCH = develop -a $TRAVIS_PULL_REQUEST = false && ./.travis/license-crawler.sh
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_EVENT_TYPE
  - echo $TRAVIS_PULL_REQUEST

# Configure notifications
notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOK_NOTIFY
      # this is just for testing; this url is only 48h active; append ?inspect to the url to see all requests
      - http://requestb.in/pc64iypc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: always   # options: [always|never|change] default: always
    on_error: always    # options: [always|never|chnage] default: always
